// Generated by gencpp from file hrwros_msgs/ConvertMeterToFeetRequest.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEETREQUEST_H
#define HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct ConvertMeterToFeetRequest_
{
  typedef ConvertMeterToFeetRequest_<ContainerAllocator> Type;

  ConvertMeterToFeetRequest_()
    : distance_meters(0.0)  {
    }
  ConvertMeterToFeetRequest_(const ContainerAllocator& _alloc)
    : distance_meters(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_meters_type;
  _distance_meters_type distance_meters;





  typedef boost::shared_ptr< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertMeterToFeetRequest_

typedef ::hrwros_msgs::ConvertMeterToFeetRequest_<std::allocator<void> > ConvertMeterToFeetRequest;

typedef boost::shared_ptr< ::hrwros_msgs::ConvertMeterToFeetRequest > ConvertMeterToFeetRequestPtr;
typedef boost::shared_ptr< ::hrwros_msgs::ConvertMeterToFeetRequest const> ConvertMeterToFeetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.distance_meters == rhs.distance_meters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddb8ee0ae0b7f759ed1a69869c0f0d7a";
  }

  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddb8ee0ae0b7f759ULL;
  static const uint64_t static_value2 = 0xed1a69869c0f0d7aULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/ConvertMeterToFeetRequest";
  }

  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance_meters     # Request message: Distance in (m) to be converted to feet\n"
;
  }

  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_meters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertMeterToFeetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::ConvertMeterToFeetRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance_meters: ";
    Printer<double>::stream(s, indent + "  ", v.distance_meters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEETREQUEST_H
