// Generated by gencpp from file hrwros_msgs/ConvertMeterToFeet.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEET_H
#define HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEET_H

#include <ros/service_traits.h>


#include <hrwros_msgs/ConvertMeterToFeetRequest.h>
#include <hrwros_msgs/ConvertMeterToFeetResponse.h>


namespace hrwros_msgs
{

struct ConvertMeterToFeet
{

typedef ConvertMeterToFeetRequest Request;
typedef ConvertMeterToFeetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConvertMeterToFeet
} // namespace hrwros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrwros_msgs::ConvertMeterToFeet > {
  static const char* value()
  {
    return "310609c29786ef3922a8f8517575f397";
  }

  static const char* value(const ::hrwros_msgs::ConvertMeterToFeet&) { return value(); }
};

template<>
struct DataType< ::hrwros_msgs::ConvertMeterToFeet > {
  static const char* value()
  {
    return "hrwros_msgs/ConvertMeterToFeet";
  }

  static const char* value(const ::hrwros_msgs::ConvertMeterToFeet&) { return value(); }
};


// service_traits::MD5Sum< ::hrwros_msgs::ConvertMeterToFeetRequest> should match
// service_traits::MD5Sum< ::hrwros_msgs::ConvertMeterToFeet >
template<>
struct MD5Sum< ::hrwros_msgs::ConvertMeterToFeetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::ConvertMeterToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::ConvertMeterToFeetRequest> should match
// service_traits::DataType< ::hrwros_msgs::ConvertMeterToFeet >
template<>
struct DataType< ::hrwros_msgs::ConvertMeterToFeetRequest>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::ConvertMeterToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrwros_msgs::ConvertMeterToFeetResponse> should match
// service_traits::MD5Sum< ::hrwros_msgs::ConvertMeterToFeet >
template<>
struct MD5Sum< ::hrwros_msgs::ConvertMeterToFeetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::ConvertMeterToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::ConvertMeterToFeetResponse> should match
// service_traits::DataType< ::hrwros_msgs::ConvertMeterToFeet >
template<>
struct DataType< ::hrwros_msgs::ConvertMeterToFeetResponse>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::ConvertMeterToFeet >::value();
  }
  static const char* value(const ::hrwros_msgs::ConvertMeterToFeetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_CONVERTMETERTOFEET_H
