uint32  num_counts           # Goal messages: number of counts to count up to
---
string reuslt_message        # Result message: simple string message for the result
---
uint32 counts_elapsed        # Feedback message:  number of counts elapsed