(cl:defpackage hrwros_msgs-srv
  (:use )
  (:export
   "CONVERTMETERTOFEET"
   "<CONVERTMETERTOFEET-REQUEST>"
   "CONVERTMETERTOFEET-REQUEST"
   "<CONVERTMETERTOFEET-RESPONSE>"
   "CONVERTMETERTOFEET-RESPONSE"
  ))

